### ISSUE TITLE
thread 'main' panicked at 'assertion failed: error_code.success()', src/main.rs:78:9

### ISSUE THREAD

**Issue by nabaruns** [CosmWasm/rust-optimizer#99]
Using `cosmwasm/workspace-optimizer:0.12.9`

Local
```
$ rustup show                             
Default host: aarch64-apple-darwin
rustup home:  /Users/xx/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.65.0 (897e37553 2022-11-02)
```

It errors out  as following
```
1.64.0-x86_64-unknown-linux-musl (default)
cargo 1.64.0 (387270bc7 2022-09-16)
Building artifacts in workspace...
Found workspace member entries: ["packages/*", "contracts/*"]
Package directories: ["xx..."]
Contracts to be built: ["xx..."]
Building "contracts/xx" ...
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /code/contracts/xx/Cargo.toml
workspace: /code/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /code/contracts/xx/Cargo.toml
workspace: /code/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /code/contracts/xx/Cargo.toml
workspace: /code/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /code/contracts/xx/Cargo.toml
workspace: /code/Cargo.toml
    Updating crates.io index
thread 'main' panicked at 'assertion failed: error_code.success()', src/main.rs:78:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [optimize] Error 101
```

**Comment by webmaster128** [comment]
You have a single `Building "contracts/xx" ...` output here. Under this there seems to be a workspace. This there seems to be multiple packages. I guess you have some unsupported project setup there. Each folder in `contracts/*` needs to be a single contract.
